### ISSUE TITLE
latest update produces server error 500 on evaluate

### ISSUE THREAD

**Issue by kpapag** [pangaea-data-publisher/fuji#303]
log

`ERROR:fuji_server.app.fuji_app:Exception on /fuji/api/v1/evaluate [POST]
Traceback (most recent call last):
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\connexion\decorators\decorator.py", line 68, in wrapper
    response = function(request)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\connexion\security\security_handler_factory.py", line 381, in wrapper
    return function(request)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\connexion\decorators\uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\connexion\decorators\validation.py", line 193, in wrapper
    response = function(request)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\connexion\decorators\response.py", line 109, in wrapper
    response = function(request)
  File "C:\Users\kosta\AppData\Roaming\Python\Python39\site-packages\connexion\decorators\parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "C:\Users\kosta\git\fuji.git\fuji_server\controllers\fair_object_controller.py", line 91, in assess_by_id
    uid_result, pid_result = ft.check_unique_persistent()
  File "C:\Users\kosta\git\fuji.git\fuji_server\controllers\fair_check.py", line 519, in check_unique_persistent
    return self.check_unique_identifier(), self.check_persistent_identifier()
  File "C:\Users\kosta\git\fuji.git\fuji_server\controllers\fair_check.py", line 510, in check_unique_identifier
    return unique_identifier_check.getResult()
  File "C:\Users\kosta\git\fuji.git\fuji_server\evaluators\fair_evaluator.py", line 103, in getResult
    self.evaluate()
  File "C:\Users\kosta\git\fuji.git\fuji_server\evaluators\fair_evaluator_unique_identifier.py", line 55, in evaluate
    idhelper = IdentifierHelper(self.fuji.id)
  File "C:\Users\kosta\git\fuji.git\fuji_server\helper\identifier_helper.py", line 110, in __init__
    print(idparts.path, idorgparts,idorgid)
UnboundLocalError: local variable 'idorgparts' referenced before assignment`

**Comment by huberrob** [comment]
What was tested here (URI, PID) ?

**Comment by huberrob** [comment]
Maybe this bug was fixed in my latest commit, can you please check?

**Comment by kpapag** [comment]
Yes, the latest pull did the trick, its functioning again as intended. Thanks!
