### ISSUE TITLE
F-UJI is not working after last release (commit 8e2194b)

### ISSUE THREAD

**Issue by jcctesolin** [pangaea-data-publisher/fuji#334]
Hi guys,

After last commit (8e2194b), F-UJI server stopped to work. It raises this error:

python3 -m fuji_server -c fuji_server/config/server.ini

```
YAML PATH /home/vagrant/workdir/fuji2/fuji/fuji_server yaml metrics_v0.5.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vagrant/workdir/fuji2/fuji/fuji_server/__main__.py", line 111, in <module>
    main()
  File "/home/vagrant/workdir/fuji2/fuji/fuji_server/__main__.py", line 58, in main
    metric_specification = config['SERVICE']['metric_specification']
  File "/usr/lib/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'metric_specification'
```

Even commenting such line in __main__.py, it still does not work;

```
ERROR:fuji_server.app.fuji_app:Exception on /fuji/api/v1/evaluate [POST]
Traceback (most recent call last):
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/connexion/security/security_handler_factory.py", line 381, in wrapper
    return function(request)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/connexion/decorators/validation.py", line 193, in wrapper
    response = function(request)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/home/vagrant/workdir/fuji2/.venv/lib/python3.8/site-packages/connexion/decorators/parameter.py", line 115, in wrapper
    return function(**kwargs)
  File "/home/vagrant/workdir/fuji2/fuji/fuji_server/controllers/fair_object_controller.py", line 71, in assess_by_id
    ft = FAIRCheck(uid=identifier,
  File "/home/vagrant/workdir/fuji2/fuji/fuji_server/controllers/fair_check.py", line 209, in __init__
    self.metric_helper = MetricHelper(metric_version)
  File "/home/vagrant/workdir/fuji2/fuji/fuji_server/helper/metric_helper.py", line 41, in __init__
    stream = open(os.path.join(metric_yml_path,metric_file_name), 'r', encoding='utf8')
NotADirectoryError: [Errno 20] Not a directory: '/home/vagrant/workdir/fuji2/fuji/fuji_server/yaml/metrics_v0.5.yaml/metrics_v0.5.yaml'
```

**Comment by rue-a** [comment]
Apparently there are some bugs in the current source. I did the following to make it run (with Python 3.11.3):

- in `pyproject.toml`, change `pyyaml = "~5.4"` to `pyyaml = "~5.3"`
- in `fuji_server/__main__.py__` (line 58), comment line `metric_specification = config['SERVICE']['metric_specification']` (there is no `'metric_specification'` in `fuji_server/config/server.ini`). Another (probably safer) option is: `metric_specification = config.get('SERVICE','metric_specification', fallback=None)`. Turns out, older versions of the `server.ini` use `metric_specification = https://doi.org/10.5281/zenodo.4081213`, I inserted this.
- in `fuji_server/__main__.py__` (line 98), make path to config file optional and provide default config: Change `parser.add_argument('-c', '--config', required=True, help='Path to server.ini config file')` to `parser.add_argument('-c', '--config', required=False, default=os.path.join(my_path, 'config/server.ini'), help='Path to server.ini config file')`
- in `fuji_server/metric_helper.py`, in line 41: change `stream = open(os.path.join(metric_yml_path,metric_file_name), 'r', encoding='utf8')` to `stream = open(metric_yml_path, 'r', encoding='utf8')` (the variable `metric_yml_path` already contains the file name, this is maybe due to the changes above)
- (optional: in `fuji_server/config/users.py`, adjust username and pw)


### install

- create an env somewhere in your filesystem `python -m venv fuji-venv`
- activate venv: `. ./fuji-venv/Scripts/activate`
- cd into changed fuji source code and run `pip install .`

### start

- start server with `python -m fuji_server` (we do not need to provide the path to the config, as we set a default)
- go to `http://localhost:1071/fuji/api/v1/ui`

**Comment by huberrob** [comment]
I am currently working on some major changes, so latest commits might be unstable in particular those I submitted before the summer break. I apologize the inconveniences and hope to be able to fix this asap . Thanks for your patience..

**Comment by afuetterer** [comment]
Hi @huberrob, this was adressed, right? Can the issue be closed then?

**Comment by afuetterer** [comment]
Pleas close @huberrob, this issue is outdated. The problem is fixed.
