### ISSUE TITLE
Bug: Preprocessor.get_licenses()

### ISSUE THREAD

**Issue by afuetterer** [pangaea-data-publisher/fuji#388]
## Steps to reproduce
```python
>>> from fuji_server.helper.preprocessor import Preprocessor
>>> Preprocessor().get_licenses()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/XXX/fuji/fuji_server/helper/preprocessor.py", line 588, in get_licenses
    cls.retrieve_licenses(cls.SPDX_URL, True)
TypeError: retrieve_licenses() takes 2 positional arguments but 3 were given
```

**Comment by huberrob** [comment]
replace with 
 cls.retrieve_licenses(True)
, but I think you did this already?

**Comment by afuetterer** [comment]
Yes, this is done. Can we remove this? 
https://github.com/pangaea-data-publisher/fuji/blob/2dd6d4ad8b793baa4240e4f78a44b89e23d96203/fuji_server/helper/preprocessor.py#L589

**Comment by huberrob** [comment]
Yes, this can be removed..
